language: php

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

os:
  - linux

sudo: false

cache:
  directories:
    - vendor/

before_script:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - phpenv config-rm xdebug.ini || echo "ext-xdebug is not available, cannot remove it, but that's OK"

script:
  - composer install
  - ./vendor/bin/phpunit tests
